# Generated by Django 4.2.7 on 2026-04-25 10:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], db_index=True, max_length=10)),
                ('amount_paise', models.BigIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='merchants.merchant')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='payouts.payout')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant', 'entry_type'], name='ledger_entr_merchan_2b8c6e_idx'), models.Index(fields=['merchant', 'created_at'], name='ledger_entr_merchan_491d5c_idx')],
            },
        ),
    ]
